apiVersion: v1
kind: Service
metadata:
  labels:
    app: webserver-service
  name: webserver-service
  namespace: webapp
spec:
  ports:
    - name: http # わかりやすい名前に変更をする
      port: 80
      protocol: TCP
      targetPort: 80
      nodePort: 30000 # 指定がない場合は30000 - 32767の範囲でランダムに割り当てをする
  selector:
    app: webserver # Podのラベルに合わせて変更をする
  type: NodePort # ClusterIP -> NodePortに変更
